services:
  - type: web
    name: tem-de-tudo
    env: php
    region: oregon
    plan: free
    buildCommand: |
      cd backend &&
      composer install --no-dev --optimize-autoloader &&
      echo "DB_CONNECTION=pgsql" > .env &&
      echo "DB_HOST=dpg-d3vps0k9c44c738q64gg-a.oregon-postgres.render.com" >> .env &&
      echo "DB_PORT=5432" >> .env &&
      echo "DB_DATABASE=tem_de_tudo_database" >> .env &&
      echo "DB_USERNAME=tem_de_tudo_database_user" >> .env &&
      echo "DB_PASSWORD=9P0c4gV4RZd8moh9ZYqGIo0BmyZ10XhA" >> .env &&
      php artisan key:generate --force &&
      php artisan cache:clear &&
      php artisan route:clear &&
      php artisan view:clear &&
      php artisan config:clear &&
      php artisan config:cache &&
      php artisan route:cache &&
      php artisan view:cache &&
      php artisan migrate --force
    startCommand: |
      cd backend &&
      php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_NAME
        value: "Tem de Tudo"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://tem-de-tudo.onrender.com
      - key: APP_LOCALE
        value: pt_BR
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d3vps0k9c44c738q64gg-a.oregon-postgres.render.com
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: tem_de_tudo_database
      - key: DB_USERNAME
        value: tem_de_tudo_database_user
      - key: DB_PASSWORD
        value: 9P0c4gV4RZd8moh9ZYqGIo0BmyZ10XhA
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_LEVEL
        value: error
    disk:
      name: tem-de-tudo-data
      mountPath: /opt/render/project/src/backend/storage
    autoDeploy: true