services:
  - type: web
    name: tem-de-tudo
    env: php
    region: oregon
    plan: free
    buildCommand: |
      cd backend &&
      composer install --no-dev --optimize-autoloader &&
      touch database/database.sqlite &&
      php artisan key:generate --force &&
      php artisan migrate --force || true
    startCommand: |
      cd backend &&
      php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
    envVars:
      - key: APP_NAME
        value: "Tem de Tudo"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:3cQV4S7tE8m2dR9wQ5lN6pK1jH0uI8yT7rE3wQ9pL5k=
      - key: APP_URL
        value: https://app-tem-de-tudo.onrender.com
      - key: APP_LOCALE
        value: pt_BR
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /opt/render/project/src/backend/database/database.sqlite
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_LEVEL
        value: error
    autoDeploy: true